"""Initial schema

Revision ID: 2c507dd1a403
Revises: 
Create Date: 2026-08-10 00:51:44.624399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c507dd1a403'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('decision_time', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decision_protocol', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('combined_signal', sa.Float(), nullable=True),
    sa.Column('debate_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_regime', sa.String(length=30), nullable=True),
    sa.Column('volatility_state', sa.String(length=20), nullable=True),
    sa.Column('market_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('expected_return_pct', sa.Float(), nullable=True),
    sa.Column('expected_risk_pct', sa.Float(), nullable=True),
    sa.Column('order_placed', sa.Boolean(), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('orchestrator_version', sa.String(length=20), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decisions')),
    sa.UniqueConstraint('decision_id', name=op.f('uq_agent_decisions_decision_id'))
    )
    op.create_index(op.f('ix_agent_decisions_decision_time'), 'agent_decisions', ['decision_time'], unique=False)
    op.create_index(op.f('ix_agent_decisions_symbol'), 'agent_decisions', ['symbol'], unique=False)
    op.create_index('ix_decisions_action', 'agent_decisions', ['action'], unique=False)
    op.create_index('ix_decisions_symbol_time', 'agent_decisions', ['symbol', 'decision_time'], unique=False)
    op.create_table('agent_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=True),
    sa.Column('market_regime', sa.String(length=30), nullable=False),
    sa.Column('volatility_state', sa.String(length=20), nullable=True),
    sa.Column('market_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('news_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('signal_direction', sa.String(length=10), nullable=False),
    sa.Column('signal_confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('predicted_return_pct', sa.Float(), nullable=False),
    sa.Column('actual_return_pct', sa.Float(), nullable=False),
    sa.Column('prediction_error_pct', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('max_adverse_excursion_pct', sa.Float(), nullable=True),
    sa.Column('max_favorable_excursion_pct', sa.Float(), nullable=True),
    sa.Column('execution_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=True),
    sa.Column('modification_proposed', sa.Boolean(), nullable=False),
    sa.Column('proposed_modification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modification_validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_experiences')),
    sa.UniqueConstraint('experience_id', name=op.f('uq_agent_experiences_experience_id'))
    )
    op.create_index(op.f('ix_agent_experiences_recorded_at'), 'agent_experiences', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_agent_experiences_symbol'), 'agent_experiences', ['symbol'], unique=False)
    op.create_index(op.f('ix_agent_experiences_trade_id'), 'agent_experiences', ['trade_id'], unique=False)
    op.create_index('ix_exp_error', 'agent_experiences', ['error_classification'], unique=False)
    op.create_index('ix_exp_outcome', 'agent_experiences', ['outcome'], unique=False)
    op.create_index('ix_exp_regime', 'agent_experiences', ['market_regime'], unique=False)
    op.create_index('ix_exp_strategy', 'agent_experiences', ['strategy_name', 'strategy_version'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_walk_forward', sa.Boolean(), nullable=False),
    sa.Column('is_out_of_sample', sa.Boolean(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('annualized_return_pct', sa.Float(), nullable=True),
    sa.Column('avg_trade_return_pct', sa.Float(), nullable=True),
    sa.Column('best_trade_pct', sa.Float(), nullable=True),
    sa.Column('worst_trade_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('avg_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_duration_days', sa.Integer(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=False),
    sa.Column('total_slippage', sa.Float(), nullable=False),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_returns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regime_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trade_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests')),
    sa.UniqueConstraint('backtest_id', name=op.f('uq_backtests_backtest_id'))
    )
    op.create_index(op.f('ix_backtests_run_at'), 'backtests', ['run_at'], unique=False)
    op.create_index('ix_bt_strategy', 'backtests', ['strategy_name', 'strategy_version'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('previous_value', sa.String(length=50), nullable=True),
    sa.Column('forecast_value', sa.String(length=50), nullable=True),
    sa.Column('actual_value', sa.String(length=50), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=False),
    sa.Column('affected_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_reaction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_events'))
    )
    op.create_index('ix_econ_country', 'economic_events', ['country'], unique=False)
    op.create_index('ix_econ_scheduled', 'economic_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_economic_events_scheduled_at'), 'economic_events', ['scheduled_at'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data'))
    )
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_tf_ts', 'market_data', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.create_index('ix_market_data_symbol_ts', 'market_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('entities_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assets_affected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_direction', sa.String(length=20), nullable=True),
    sa.Column('expected_magnitude', sa.String(length=20), nullable=True),
    sa.Column('expected_time_horizon', sa.String(length=20), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('expected_volatility', sa.String(length=20), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('historical_analogues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_direction', sa.String(length=20), nullable=True),
    sa.Column('actual_magnitude_pct', sa.Float(), nullable=True),
    sa.Column('reaction_time_minutes', sa.Integer(), nullable=True),
    sa.Column('reaction_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_correct', sa.Boolean(), nullable=True),
    sa.Column('raw_sentiment_score', sa.Float(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_events'))
    )
    op.create_index('ix_news_category', 'news_events', ['category'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index('ix_news_processed', 'news_events', ['processed'], unique=False)
    op.create_index('ix_news_published', 'news_events', ['published_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_order_id', sa.String(length=50), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('trail_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('time_in_force', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('risk_check_passed', sa.Boolean(), nullable=True),
    sa.Column('risk_check_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('client_order_id', name=op.f('uq_orders_client_order_id'))
    )
    op.create_index('ix_orders_env_status', 'orders', ['environment', 'status'], unique=False)
    op.create_index('ix_orders_submitted', 'orders', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_symbol_status', 'orders', ['symbol', 'status'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl_pct', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('total_pnl_pct', sa.Float(), nullable=False),
    sa.Column('peak_value', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('total_exposure', sa.Float(), nullable=False),
    sa.Column('long_exposure', sa.Float(), nullable=False),
    sa.Column('short_exposure', sa.Float(), nullable=False),
    sa.Column('net_exposure', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('num_positions', sa.Integer(), nullable=False),
    sa.Column('positions_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sector_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_class_exposure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index('ix_portfolio_env_time', 'portfolio_snapshots', ['environment', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_time'), 'portfolio_snapshots', ['snapshot_time'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl_pct', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trailing_stop', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('portfolio_weight_pct', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('asset_class', sa.String(length=50), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('trade_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index('ix_positions_env', 'positions', ['environment'], unique=False)
    op.create_index('ix_positions_symbol_env', 'positions', ['symbol', 'environment'], unique=True)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('limit_name', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('limit_value', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('portfolio_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events'))
    )
    op.create_index(op.f('ix_risk_events_event_time'), 'risk_events', ['event_time'], unique=False)
    op.create_index('ix_risk_severity', 'risk_events', ['severity'], unique=False)
    op.create_index('ix_risk_type_time', 'risk_events', ['event_type', 'event_time'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_return_pct', sa.Float(), nullable=True),
    sa.Column('expected_volatility', sa.Float(), nullable=True),
    sa.Column('expected_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(length=20), nullable=True),
    sa.Column('market_regime', sa.String(length=30), nullable=True),
    sa.Column('volatility_state', sa.String(length=20), nullable=True),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('component_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_return_pct', sa.Float(), nullable=True),
    sa.Column('signal_correct', sa.Boolean(), nullable=True),
    sa.Column('strategy_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_time', 'signals', ['symbol', 'generated_at'], unique=False)
    op.create_index('ix_signals_type_source', 'signals', ['signal_type', 'source'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('supported_assets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_regimes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_timeframes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_version', sa.String(length=20), nullable=True),
    sa.Column('promotion_level', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name=op.f('uq_strategies_name'))
    )
    op.create_table('strategy_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_time', sa.DateTime(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('from_level', sa.String(length=20), nullable=False),
    sa.Column('to_level', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('criteria_met', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('human_approved', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_promotions'))
    )
    op.create_index('ix_promo_strategy', 'strategy_promotions', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_strategy_promotions_promotion_time'), 'strategy_promotions', ['promotion_time'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_sys_type_time', 'system_events', ['event_type', 'event_time'], unique=False)
    op.create_index(op.f('ix_system_events_event_time'), 'system_events', ['event_time'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_start', sa.DateTime(), nullable=True),
    sa.Column('training_end', sa.DateTime(), nullable=True),
    sa.Column('validation_start', sa.DateTime(), nullable=True),
    sa.Column('validation_end', sa.DateTime(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('avg_trade_return_pct', sa.Float(), nullable=True),
    sa.Column('calmar_ratio', sa.Float(), nullable=True),
    sa.Column('regime_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('backtest_passed', sa.Boolean(), nullable=True),
    sa.Column('walk_forward_passed', sa.Boolean(), nullable=True),
    sa.Column('out_of_sample_passed', sa.Boolean(), nullable=True),
    sa.Column('paper_trading_passed', sa.Boolean(), nullable=True),
    sa.Column('statistical_significance', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions'))
    )
    op.create_index('ix_sv_strategy_version', 'strategy_versions', ['strategy_id', 'version'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('trailing_stop', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('max_adverse_excursion', sa.Float(), nullable=True),
    sa.Column('max_favorable_excursion', sa.Float(), nullable=True),
    sa.Column('mae_pct', sa.Float(), nullable=True),
    sa.Column('mfe_pct', sa.Float(), nullable=True),
    sa.Column('expected_entry_price', sa.Float(), nullable=True),
    sa.Column('expected_slippage', sa.Float(), nullable=True),
    sa.Column('actual_slippage', sa.Float(), nullable=True),
    sa.Column('execution_quality_score', sa.Float(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('strategy_version', sa.String(length=20), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('market_regime', sa.String(length=30), nullable=True),
    sa.Column('volatility_state', sa.String(length=20), nullable=True),
    sa.Column('market_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mistake_classification', sa.String(length=100), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['agent_decisions.id'], name=op.f('fk_trades_decision_id_agent_decisions')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_trades_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('trade_id', name=op.f('uq_trades_trade_id'))
    )
    op.create_index('ix_trades_env_status', 'trades', ['environment', 'status'], unique=False)
    op.create_index('ix_trades_strategy', 'trades', ['strategy_name', 'strategy_version'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_time', 'trades', ['symbol', 'entry_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_symbol_time', table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index('ix_trades_strategy', table_name='trades')
    op.drop_index('ix_trades_env_status', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_sv_strategy_version', table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_system_events_event_time'), table_name='system_events')
    op.drop_index('ix_sys_type_time', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_strategy_promotions_promotion_time'), table_name='strategy_promotions')
    op.drop_index('ix_promo_strategy', table_name='strategy_promotions')
    op.drop_table('strategy_promotions')
    op.drop_table('strategies')
    op.drop_index('ix_signals_type_source', table_name='signals')
    op.drop_index('ix_signals_symbol_time', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_risk_type_time', table_name='risk_events')
    op.drop_index('ix_risk_severity', table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_time'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_positions_symbol_env', table_name='positions')
    op.drop_index('ix_positions_env', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_time'), table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_env_time', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_orders_symbol_status', table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index('ix_orders_submitted', table_name='orders')
    op.drop_index('ix_orders_env_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_news_published', table_name='news_events')
    op.drop_index('ix_news_processed', table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index('ix_news_category', table_name='news_events')
    op.drop_table('news_events')
    op.drop_index('ix_market_data_symbol_ts', table_name='market_data')
    op.drop_index('ix_market_data_symbol_tf_ts', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_economic_events_scheduled_at'), table_name='economic_events')
    op.drop_index('ix_econ_scheduled', table_name='economic_events')
    op.drop_index('ix_econ_country', table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index('ix_bt_strategy', table_name='backtests')
    op.drop_index(op.f('ix_backtests_run_at'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index('ix_exp_strategy', table_name='agent_experiences')
    op.drop_index('ix_exp_regime', table_name='agent_experiences')
    op.drop_index('ix_exp_outcome', table_name='agent_experiences')
    op.drop_index('ix_exp_error', table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_trade_id'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_symbol'), table_name='agent_experiences')
    op.drop_index(op.f('ix_agent_experiences_recorded_at'), table_name='agent_experiences')
    op.drop_table('agent_experiences')
    op.drop_index('ix_decisions_symbol_time', table_name='agent_decisions')
    op.drop_index('ix_decisions_action', table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_symbol'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_decision_time'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
